name: flutter_blue_example
description: Demonstrates how to use the flutter_blue plugin.
publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.2+1
  path_provider: ^2.0.10
  syncfusion_flutter_charts: ^20.4.44
  flutter_jailbreak_detection: ^1.10.0
  encrypt: ^5.0.1
  flutter_secure_storage: ^8.0.0
  permission_handler: ^10.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_blue:
   path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/images/
